### ISSUE TITLE
Frame rate of .pose does not match original .mp4

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/pose#101]
As a test, I ran `video_to_pose` on https://deafbible.com/ASLV/JHN.3.1, and then tried to generate an overlay video. 

I received an error saying that the frame rates did not match, 29.97 != 29.0, throwing an error. 

Apparently [this is likely caused by the fact that `pose-format` stores frame rate as an unsigned short](https://signlanguager-kgn3800.slack.com/archives/CR6D4TCQM/p1723760117324569?thread_ts=1723754625.804579&cid=CR6D4TCQM)

https://github.com/sign-language-processing/pose/blob/master/docs/specs/v0.1.md#body

I should be able to upload the stack trace soon. 

From memory, what I did was based on the instructions from https://colab.research.google.com/drive/1CKlXVI3vP0NKZDZZ_I-Qb_wSHt2cw4VT, trying to run pose estimation and segmentation on a new video. Something like:

1. download https://deafbible.com/ASLV/JHN.3.1, the FPS is 29.97ish
2. run `video_to_pose` on it
3. run the visualizer/overlay function on it to generate .pose.overlay.mp4 
4. the overlay function throws an error, saying that the frame rates don't match, 29.97 vs 29.0

edit: Stack trace: 
```
Traceback (most recent call last):
  File "/home/cleong/projects/sign_language/video-to-pose-to-segments/overlay_pose_vid.py", line 45, in <module>
    output_path = pose_visualize(pose_path=str(args.pose_file), video_path=str(args.video_file))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cleong/projects/sign_language/video-to-pose-to-segments/overlay_pose_vid.py", line 27, in pose_visualize
    v.save_video(output_path, v.draw_on_video(video_path))
  File "/home/cleong/miniconda3/envs/signsegment/lib/python3.12/site-packages/pose_format/pose_visualizer.py", line 402, in save_video
    for frame in tqdm(frames):
  File "/home/cleong/miniconda3/envs/signsegment/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/cleong/miniconda3/envs/signsegment/lib/python3.12/site-packages/pose_format/pose_visualizer.py", line 236, in draw_on_video
    for frame, confidence, background in itertools.islice(
  File "/home/cleong/miniconda3/envs/signsegment/lib/python3.12/site-packages/pose_format/pose_visualizer.py", line 223, in get_frames
    assert math.isclose(video_fps, self.pose_fps, abs_tol=0.5), \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Fps of pose and video do not match: 29.000000 != 29.970030
```

The precise frame rate of the video as reported by ffmpeg:
```
ffprobe -v error -select_streams v:0 -show_entries stream=avg_frame_rate -of default=noprint_wrappers=1:nokey=1 toying_data/ASLV/aslv_43_john-3_1-21.mp4 
30000/1001
```

**Comment by AmitMY** [comment]
Fixed in https://github.com/sign-language-processing/pose/commit/814a713c2374c1622aa30c255571f3d2c0342768
