### ISSUE TITLE
Saving modified pose data

### ISSUE THREAD

**Issue by OlineRanum** [sign-language-processing/pose#115]
Hello,

I have been trying to save preprocessed landmark data and confidence back into the .pose format but I encounter the following issues:

1. the pose.write(file) function references the write function in the Pose class, which references the write function in the PoseBody class. However, this class has not yet been implemented.

2. I have tried to implement my own BodyPose.write() function (see code 2 below), but I keep getting a type error in line 103 of utils/reader.py, stating that the 'buffer is too small for requested array'. This is likely due to a misunderstanding on my behalf regarding the functionalities of the buffer.

**Could you perhaps update the PoseBody.write() class?** Thank you very much for the assistance! 

Code 1 - poseloader.py:
```
from pose_format import Pose
import numpy.ma as ma
import numpy as np



class PoseLoader:
    def __init__(self, path="A.pose"):
        self.pose_path = path

    def load_pose(self):
        """
        Load pose data from the file.

        :return: Tuple of numpy data and confidence measure.
        """
        with open(self.pose_path, "rb") as file:
            data_buffer = file.read()
        
        self.pose = Pose.read(data_buffer)
        print('Data: ', type(self.pose.body.data), self.pose.body.data.shape, self.pose.body.data.dtype)
        print('Conf: ', type(self.pose.body.confidence), self.pose.body.confidence.shape, self.pose.body.confidence.dtype,'\n')
        
        data = self.pose.body.data.data
        conf = self.pose.body.confidence

        return data, conf

    def save_pose(self, data, conf, save_path="updated_pose.pose"):
        """
        Save updated pose data to a file.
        """

        if isinstance(data, np.ndarray):  
            mask = conf == 0  # 0 means no-confidence (masked)
            stacked_mask = np.stack([mask] * data.shape[-1], axis=3)
            masked_data = ma.masked_array(data, mask=stacked_mask)

        else:
            masked_data = data  

        self.pose.body.data = masked_data
        self.pose.body.confidence = conf

        with open("output_pose.pose", "wb") as f:
            self.pose.write(f)
        
        print(f"Pose data updated and saved to {save_path}")

    def preprocess_pose(self, feat, conf):
        # Trim 1/3 of the video from the start and the end
        n_frames = feat.shape[0]  
        trim_start = n_frames // 3  # Calculate the start index for trimming
        trim_end = 2 * n_frames // 3  # Calculate the end index for trimming

        feat = feat[trim_start:trim_end,:, :, :]
        conf = conf[trim_start:trim_end, :, :]

        # get the right hand
        feat = feat[:, :, :543, :]
        feat = feat[:, :, -21:, :].squeeze(1)

        conf = conf[:, :, :543]
        conf = conf[:, :, -21:]

        # Normalize size
        flat_array = feat.reshape(-1, 3)
          
        # Find the min and max for x and y coordinates
        min_vals = np.min(flat_array, axis=0)  # Min of x and y
        max_vals = np.max(flat_array, axis=0)  # Max of x and y
        
        # Normalize the array
        # This is a simple min max norm 
        feat = (feat - min_vals) / (max_vals - min_vals)
        
        # Temporal Normalization	
        keypoints_array_squeezed = feat  # Shape (num_frames, num_keypoints, 3)
        for i in range(keypoints_array_squeezed.shape[0]):
            keypoints = keypoints_array_squeezed[i]  # Shape (num_keypoints, 3)

            # Check if there are enough keypoints to access the 6th one
            if keypoints.shape[0] > 6:
                # Extract x, y, and z coordinates
                x, y, z = keypoints[:, 0], keypoints[:, 1], keypoints[:, 2]

                # Subtract the 6th keypoint's x, y, and z coordinates to normalize all dimensions
                x_shifted = x - x[6]
                y_shifted = y - y[6]
                z_shifted = z - z[6]

                # Update the keypoints array with the shifted x, y, and z coordinates
                keypoints_array_squeezed[i, :, 0] = x_shifted
                keypoints_array_squeezed[i, :, 1] = y_shifted
                keypoints_array_squeezed[i, :, 2] = z_shifted

        # Reshape back to the original format (num_frames, 1, num_keypoints, 3)
        feat = keypoints_array_squeezed
        feat =  keypoints_array_squeezed[:, np.newaxis, :, :]

        return feat, conf
              

if __name__ == "__main__":

    print('Reading original pose')
    pose_loader = PoseLoader("signbank_poses/#A.pose")
    pose, conf = pose_loader.load_pose()    
  

    # Extract normalized right hand keypoints
    pose_R, conf = pose_loader.preprocess_pose(pose, conf)

    # Save pose with fewer frames and 21 keypoints
    print('\nWriting to new pose')
    pose_loader.save_pose(pose_R, conf)

    print('\nReading updated pose')
    pose_loader = PoseLoader("output_pose.pose")
    pose, conf = pose_loader.load_pose()
        
```

Code 2 - Bodypose.write():
```
    def write(self, version: float, buffer: BinaryIO):
        """
        Writes pose data to a binary buffer using specified data format version.

        Parameters
        ----------
        version : float
            Version of the data format.
        buffer : BinaryIO
            The binary buffer to write to.
        """
        

        # Write FPS to the buffer
        buffer.write(ConstStructs.float.pack(self.fps))
        
        _frames, _people, _points, _dims = self.data.shape
        
        buffer.write(ConstStructs.uint.pack(_frames))
        buffer.write(ConstStructs.ushort.pack(_people))
        

        self.confidence = np.ascontiguousarray(self.confidence)
        # Write the data to the buffer
        print('Data: ', type(self.data), self.data.shape, self.data.dtype)
        print('Conf: ', type(self.confidence), self.confidence.shape, self.confidence.dtype)
        buffer.write(self.data)
        buffer.write(np.ascontiguousarray(self.confidence))
```

Resulting Output
```
(fairseq) (base) gomer@monsterfish001:~/oline$ python poseloader.py
Reading original pose
Dimensions read from data file:
frames:  76 , shape: (1, 576, 3)
Dimensions read from data file:
frames:  76 , shape: (1, 576)
Data:  <class 'numpy.ma.core.MaskedArray'> (76, 1, 576, 3) float32
Conf:  <class 'numpy.ndarray'> (76, 1, 576) float32 


Writing to new pose
Data:  <class 'numpy.ma.core.MaskedArray'> (25, 1, 21, 3) float32
Conf:  <class 'numpy.ndarray'> (25, 1, 21) float32
Pose data updated and saved to updated_pose.pose

Reading updated pose
Dimensions read from data file:
frames:  25 , shape: (1, 576, 3)
Traceback (most recent call last):
  File "pl3.py", line 120, in <module>
    pose, conf = pose_loader.load_pose()
  File "pl3.py", line 20, in load_pose
    self.pose = Pose.read(data_buffer)
  File "/home/gomer/miniconda3/envs/fairseq/lib/python3.8/site-packages/pose_format/pose.py", line 51, in read
    body = pose_body.read(header, reader, **kwargs)
  File "/home/gomer/miniconda3/envs/fairseq/lib/python3.8/site-packages/pose_format/pose_body.py", line 65, in read
    return cls.read_v0_2(header, reader, **kwargs)
  File "/home/gomer/miniconda3/envs/fairseq/lib/python3.8/site-packages/pose_format/pose_body.py", line 228, in read_v0_2
    data = cls.read_v0_1_frames(_frames, (_people, _points, _dims), reader, start_frame, end_frame)
  File "/home/gomer/miniconda3/envs/fairseq/lib/python3.8/site-packages/pose_format/pose_body.py", line 145, in read_v0_1_frames
    tensor = tensor_reader(ConstStructs.float, shape=(_frames, *shape))
  File "/home/gomer/miniconda3/envs/fairseq/lib/python3.8/site-packages/pose_format/utils/reader.py", line 100, in unpack_numpy
    arr = np.ndarray(shape, s.format, self.buffer, self.read_offset).copy()
TypeError: buffer is too small for requested array
```

**Comment by AmitMY** [comment]
`pose.body.data` of a `NumpyPoseBody` must be a masked array, not a numpy array. I believe that is the issue you are having.

To showcase it, start with this working code:
```py
with open("example.pose", "rb") as file:
        pose = Pose.read(file.read())

with open("example2.pose", "wb") as file:
        pose.write(file)
```

Then, spring the body types:
```py
print(type(pose.body.data), pose.body.data.shape, pose.body.data.dtype)
print(type(pose.body.confidence), pose.body.confidence.shape, pose.body.confidence.dtype)
```

Now, print them after your modification.
Let me know what the two outputs are, and I will likely be able to tell you the issue. Right now your code is incomplete for a reproduction (`preprocess_pose` is missing)

**Comment by AmitMY** [comment]
If you are reducing the number of keypoints, you need to also update the header to the correct list of keypoints, that way it saves the metadata in the same file. 

There is a way in the library, to specify what points and components you want, and the data array changes accordingly. See this example:
https://github.com/sign-language-processing/pose/blob/43a303e73d5d0eddd3f463ae28b1268b4f751fe2/src/python/pose_format/utils/generic.py#L157

We choose some points for each component, then choose certain components.

It is very important to keep the header and body in sync. It means that you can visualize, and query the pose by the point names, not by indexes. It means that the pose file itself is self contained.

**Comment by OlineRanum** [comment]
Great, thank you so much for the help Amit!
